services:
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    ports:
      - '9081:81'
      - '9080:80'
      - '9443:443'
    volumes:
      - ./data:/data

  ssoalert:
    build: ./
    container_name: sso-alert
    ports:
      - "8080:8080"
    volumes:
      - ./:/code
    depends_on:
      - db
    environment:
      - USE_POSTGRES=True
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}

  db:
    image: postgres:12.1
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
