# Generated by Django 4.2.9 on 2024-05-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso_alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertstreams',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
