# Generated by Django 4.2.9 on 2024-05-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso_alerts', '0002_alter_alertstreams_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertstreams',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
