# Generated by Django 4.2.9 on 2024-05-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chained', '0002_templatedchain_chainedtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatedchain',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
