# Generated by Django 4.2.9 on 2024-05-07 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chained', '0004_templatedchain_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chainedtemplate',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
